# Generated by Django 4.1.7 on 2023-10-02 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('grade', models.CharField(max_length=2)),
                ('school_name', models.CharField(max_length=100)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=2)),
            ],
        ),
    ]
